### ISSUE TITLE
`3d6^2s` raises, `3d6^2t` doesn't total.

### ISSUE THREAD

**Issue by mikevb1** [borntyping/python-dice#10]
Noticed a slight discrepancy here, at least from user standpoint.
`3d6^2t` doesn't error, but it doesn't total the result either. `3d6^2s` errors with `AttributeError: 'Integer' object has no attribute 'sort'`.

Possible solution could be to just strip t/s off the end, evaluate, then total/sort?

**Comment by borntyping** [comment]
Sorry, still haven't found the time to look into this. At a guess this is being evaluated as `(3d6)^(2s)` (`2s` highest rolls from `3d6`), rather than `(3d6^2)s` (sort rolls from `3d6^2`).
