### ISSUE TITLE
Add support to duplicate a result

### ISSUE THREAD

**Issue by psychomantys** [borntyping/python-dice#14]
In some RPG systems(storyteller for example), there is a chance that each played dice explodes for the same result without having to roll again.

For storyteller(in some cases):

* For **each rolled dice**, if it is **10**, add a **10** again.
* For **each rolled dice**, if it is **1**, add a **1** again.

It's a feature request, if possible, can be implemented something like this?

Possible syntax suggestions would be:

```python
dice.roll("(10|10|10)xx10")
[10, 10, 10, 10, 10, 10]
```

Or a new letter:

```python
dice.roll("(1|1|1)a1")
[1, 1, 1, 1, 1, 1]
```

The goal is to be able to do something like this in the end:

```python
dice.roll("(((7d10)xx1)xx10)f8")
2
```

Or:

```python
dice.roll("(((7d10)xx1)xx10)f8")
-1
```

Thanks!

**Comment by calebj** [comment]
This sounds like a reasonable feature. I think I'll use the letter `a` for 'again', as in the 10 Again rule you mentioned from Storyteller.

The only confusion I have is whether the *value* or the *element* should be repeated. From what I can tell, the 10 Again rule adds another *d*10, which is functionally identical to the existing `x` operator.

**Comment by psychomantys** [comment]
Nice.

> The only confusion I have is whether the value or the element should be repeated. From what I can tell, the 10 Again rule adds another d10, which is functionally identical to the existing x operator.

Repeat the *value* on list.

More examples:

<hr/>

Rolling `3D10`, with dice result of **"10, 5, 3"** and double the values **10**:

```python
dice.roll("(3d10)a10")
[10,10,5,3]
```

The first value **10** is double. No rerolls involved.

<hr/>

Or, rolling `3D10`, with dice result of **"10, 5, 1"** and double the values **1**:

```python
dice.roll("(3d10)a1")
[10,5,1,1]
```

The final value of list **1** is double.

<hr/>

Or, a more exoteric example, rolling `4D8`, with dice result of **"8, 8, 5,5"** and double the values **5**:

```python
dice.roll("(4d10)a5")
[8,8,5,5,5,5]
```

The two values **5** at the end is doubled.

<hr/>

If it's not clear, I can go into more detail.

Sorry for not speaking English so well, anyway. And thanks for the reply!

**Comment by psychomantys** [comment]
Thanks!!

(Y)
