### ISSUE TITLE
Cannot roll less than zero dice error

### ISSUE THREAD

**Issue by Wiadomy** [borntyping/python-dice#18]
When I'm trying to evaluate expression `(5+(-10))d10`. However with `-5d10` it works correctly (`[-3, -2, -3, -1, -1]`)

```
  File "/usr/local/lib/python3.6/site-packages/dice/__init__.py", line 24, in roll
    return _roll(string, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/dice/__init__.py", line 58, in _roll
    raise DiceBaseException.from_other(e)
dice.exceptions.DiceFatalException: Cannot roll less than zero dice! (Add(5, -10) evaluated to -5) (at char 0), (line:1, col:1)
```

**Comment by borntyping** [comment]
I think `(5+(-10))d10` gets evaluated to `(-5)d(10)` and errors, and `-5d10` evaluates to `-((5)d(10))`, rolling 5 dice and making each result negative.

**Comment by Wiadomy** [comment]
Yes, that's right.

**Comment by Wiadomy** [comment]
The interesting thing is, `maxroll` gives output (0) with the same expression (-5)d5 and `roll` doesn't. Or is it just my parser?

**Comment by calebj** [comment]
Min/max rolls short-circuit some of the evaluation code and return `[min_value] * amount` or `[max_value] * amount`, which results in an empty list when amount < 1. It *should* return an error, though, so I'll fix it soon.

Sam is right about the other things; the `d` operator has a higher precedence than the unary minus sign, so `-5d10` evaluates to: `Negate(roll 5d10 -> [1, 5, 7, 5, 2]) -> [-1, -5, -7, -5, -2]`

Oh, and if you're using discord.py, I have a dice cog for Red [here](https://github.com/calebj/calebj-cogs/blob/master/dice/dice.py) that you can use as a base, if you want.

**Comment by calebj** [comment]
This should be fixed in 3ce27ecb3d0ef54fcac4bdf0ca7a81d45af79c45, can you verify?

**Comment by Wiadomy** [comment]
Yes, error message shows up now.

**Comment by calebj** [comment]
Alright then, I'm closing this.
