### ISSUE TITLE
Wrong version from CLI

### ISSUE THREAD

**Issue by pedro-w** [borntyping/python-dice#27]
Not the most serious issue in the world but:

```
> roll -V
dice v2.4.1 by Sam Clements <sam@borntyping.co.uk>, Caleb Johnson <me@calebj.io>
```

Should be `v3.1.0` I believe.

Thanks for dice, it's great!

**Comment by borntyping** [comment]
Thanks! Uploaded to pypi as https://pypi.org/project/dice/3.1.1/.
