### ISSUE TITLE
Please add explode, reroll

### ISSUE THREAD

**Issue by blade2005** [borntyping/python-dice#8]
I'd love to use this library but I can't use it without the features of explode and reroll. I see these feature present in https://github.com/borntyping-sandbox/diceroll but they never seemed to make it over to this version.

Was there a specific reasoning on not porting this over?

**Comment by borntyping** [comment]
Not that I know of, but it'll been a very long time since I worked on either. I'll see what I can do, but in the meantime PRs are welcome :)

**Comment by blade2005** [comment]
*picks up tutorial on pyparsing*

I'll take a look pretty soon see how hard it is to backport it.
